### ISSUE TITLE
Favor immutable value types over mutable reference types

### ISSUE THREAD

**Issue by cellularmitosis** [izzy5455/GoNoGo#2]
Hey!

This is a great first effort!

Here is an exercise for you:
- Watch "Enemy of the State" by Justin Spahr-Summers: https://www.youtube.com/watch?v=7AqXBuJOJkY
- Try to refactor `class GoImage` to adhere to his advice.

Your refactor could take place in two steps:
- Try to replace the mutable variables (`var`) in `GoImage` with constants (`let`).
- Try to change `GoImage` from a `class` (reference type) into a `struct` (value type).

Good luck!  In a few days I'll submit a pull-request with my attempt at these changes.

**Comment by n0obscertified** [comment]
Hey thanks for the input i will definitely watch the video most likely tomorrow and the goImage class is now a struct and everything inside a let. However there are plenty of other issues if you want to help 👍
